### PR TITLE
Wait for all probes to be installed before starting the collection

### LINKED ISSUE #312: Early tracking might be wrong
Probes are installed sequentially and not in order. When matching packets while not all probes are installed, especially the ones required for the tracking infrastructure, we might have wrong tracking information as free events could be missed.

One easy way to see this is to install lots of probes (eg. `-p skb*`) while filtering on an IPv4 address. Before all probes are installed, if packets are matches, we might see unexpected events (here IPv6 or wrong address).

One solution might be to control the order in which those important probes are being installed.

### PR DESCRIPTION
**Pull request by atenart**
Not doing so lead to various issues such as:
- Inconsistency about what events are reported for a given flow.
- Tracking issues as not all tracking probes are installed (leading to unrelated flows sharing the same tracking id, or stalled entries in the tracking map).
    
This also opens the door for having other shared configuration options among all probes.
    
Fixes #312. Includes the same probe manager reworks as #309 but does not depend on it.

### CODE REVIEW

**Comment by vlrpl** [comment]
can you please rebase this?

**Comment by atenart** [comment]
> can you please rebase this?

Sure, thanks for pinging me. Turns out git can rebase this automatically but not merge :)

File: src/core/probe/kernel/bpf/include/common.h [hunk 1]
```diff
@@ -210,10 +210,20 @@ static __always_inline int chain(struct retis_context *ctx)
...
 	struct common_task_event *ti;
+	static bool enabled = false;
 	volatile u16 pass_threshold;
 	struct common_event *e;
 	struct kernel_event *k;
 
+	/* Check if the collection is enabled, otherwise bail out. Once we have
+	 * a positive result, cache it.
+	 */
+	if (!enabled) {
```
Comment (vlrpl) [inline src/core/probe/kernel/bpf/include/common.h:221]: what about adding this in a common header (common_defs.h)?:

```c
#ifndef likely
#define likely(x)	__builtin_expect(!!(x), 1)
#endif

#ifndef unlikely
#define unlikely(x)	__builtin_expect(!!(x), 0)
#endif
```

and use it here?

File: src/core/probe/user/bpf/usdt.bpf.c [hunk 2]
```diff
@@ -52,12 +52,22 @@ int probe_usdt(struct pt_regs *ctx)
...
+	struct user_ctx uctx = {};
 	struct common_event *e;
-	struct retis_raw_event *event;
 	struct user_event *u;
-	struct user_ctx uctx = {};
+
+	/* Check if the collection is enabled, otherwise bail out. Once we have
+	 * a positive result, cache it.
+	 */
+	if (!enabled) {
```
Comment (vlrpl) [inline src/core/probe/user/bpf/usdt.bpf.c:66]: ditto

File: src/core/probe/kernel/bpf/include/common.h (hunk 1 above)
Comment (atenart) [reply src/core/probe/kernel/bpf/include/common.h:221]: I think that makes sense; if that indeed makes a difference when building BPF programs (it seems some are using that so I guess so).

Comment (vlrpl) [reply src/core/probe/kernel/bpf/include/common.h]: it makes a difference in the build

**Comment by atenart** [comment]
Rebased on top of main to fix a linter issue. No other change intended.

**Review by vlrpl — APPROVED** [review]
lgtm, thanks!
